name: Release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  release:
    name: push to rubygems
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - uses: rubygems/release-gem@v1
